/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GwfMainVis {
    }
}
declare global {
    interface HTMLGwfMainVisElement extends Components.GwfMainVis, HTMLStencilElement {
    }
    var HTMLGwfMainVisElement: {
        prototype: HTMLGwfMainVisElement;
        new (): HTMLGwfMainVisElement;
    };
    interface HTMLElementTagNameMap {
        "gwf-main-vis": HTMLGwfMainVisElement;
    }
}
declare namespace LocalJSX {
    interface GwfMainVis {
    }
    interface IntrinsicElements {
        "gwf-main-vis": GwfMainVis;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gwf-main-vis": LocalJSX.GwfMainVis & JSXBase.HTMLAttributes<HTMLGwfMainVisElement>;
        }
    }
}
